version: '2'

services:
    payment:
        build: 
            context: .
            dockerfile: docker/payment/Dockerfile
        image: azumax/payment
        hostname: payment
        restart: always
        cap_drop:
            - all
        cap_add:
            - NET_BIND_SERVICE
        read_only: true
        environment:
            - reschedule=on-node-failure
            - NEW_RELIC_APP_NAME=micro-payment
            - NEW_RELIC_LICENSE_KEY=***
        ports:
            - "8082:80"
